name: safe_notes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  #cryptography
  encrypt: ^5.0.1

  # Structure
  flutter_modular: ^4.5.1+1
  flutter_triple: ^1.2.7+2
  rx_notifier: ^1.1.0

  # Others
  package_info_plus: ^1.4.2
  fpdart: ^0.0.14

  # Core
  shared_preferences: ^2.0.13
  floor: ^1.2.0

  #cloud
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  
  mocktail: ^0.3.0
  triple_test: ^1.0.0
  modular_test: ^1.0.1+2
  floor_generator: ^1.2.0
  build_runner: ^2.1.8
  firebase_auth_mocks: ^0.8.4
  fake_cloud_firestore: ^1.2.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-Italic.ttf
          style: italic
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
